server.port=7070
spring.application.name=policy

spring.datasource.url=jdbc:sqlite:polizas.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect